djangomerge/blog/urls.py
from django.urls import path
from . import views
#from django.conf import settings
#from django.conf.urls.static import static
app_name="blog"

urlpatterns = [
    path('post/<slug:slug>/edit/', views.post_edit, name='post_edit'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('post/<slug:slug>', views.post_detail, name='post_detail'),
    path('tag/<slug:slug>', views.tag, name='tag'),
    path('profile/edit/',views.profile_edit, name='profile-edit'),
    path('signup/login/',views.login_request,name='login2'),
    path('post/new/', views.post_new, name='post_new'),
    path('signup/', views.signup_request, name='signup'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('profile/',views.profile_request, name='users-profile'),
    path('comment/', views.post_detail, name= 'comment'),
    path('', views.post_list, name='post_list'),
 ]

djangomerge/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('polls/', include('polls.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangomerge/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from django_extensions.db.fields import AutoSlugField
from django.utils.safestring import mark_safe
from django_ckeditor_5.fields import CKEditor5Field

class User(AbstractUser):
    email = models.EmailField(max_length=255,blank=True,null=True)
    gender = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    mobile_no = models.CharField(max_length=15)
    image = models.ImageField(upload_to ='image/')

    
    def __str__(self):
        return self.email

class Category(models.Model):
    
    name = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from=('name'), unique=True, max_length=255)
    
    
    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

class Tag(models.Model):
    
    name=models.CharField(max_length=200)
    slug = AutoSlugField(populate_from=('name'), unique=True, max_length=255)
    

    def __str__(self):
        return self.name

class Post(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    slug = AutoSlugField(populate_from=('title'), unique=True, max_length=255)
    text = CKEditor5Field('Text', config_name='extends')
    featured_image = models.ImageField(upload_to="featured_images/")
    thumbnail_image = models.ImageField(upload_to="thumbnail_images/")
    created_date=models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(blank=True,null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    
    def thumbnail(self): 
        return mark_safe(f'<img src = "{self.thumbnail_image.url}" width = "150"/>')
         
    def featured(self): 
        return mark_safe(f'<img src = "{self.featured_image.url}" width = "150"/>')
         
    def publish(self):
        self.published_date=timezone.now()
        self.save()
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, null=True, blank=True)
    comment = models.TextField(max_length = 1000, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=now)
    parent = models.ForeignKey('self' , null=True , blank=True , on_delete=models.CASCADE , related_name='replies')

    class Meta:
        ordering = ('-timestamp',)

    def __str__(self):
        return self.name
    
    @property
    def children(self):
        return Comment.objects.filter(parent=self).reverse()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False

djangomerge/blog/forms.py
from django import forms

from .models import *

class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].required = False
        
    class Meta:
        model = Post
        fields = ('title', 'text','featured_image','thumbnail_image','category','tag')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget = forms.PasswordInput)

    class Meta:
        model = User
        fields = ('image','first_name','last_name','email','mobile_no','username','city','country','gender')

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'comment')

djangomerge/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Post, User, Category, Tag, Comment
from .forms import *
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

def post_list(request):
	posts=Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request, 'blog/post_list.html', {'posts':posts})

def post_detail(request, slug):
	post = get_object_or_404(Post, slug=slug)
	comments = Comment.objects.filter(post=post)
	print(comments)
	if request.method == "POST":
		form = CommentForm(request.POST)
		if form.is_valid():
			try :
				parent = request.POST.get('comment_id')
				parent = Comment.objects.filter(id = parent).last()
				print(parent, 'parent instanceeeee')
			except:
				parent=None
			comments = form.save(commit=False)
			comments.post = post
			comments.parent = parent
			comments.save()
		return redirect('blog:post_detail', slug=post.slug)
	else:
		form  = CommentForm()
	return render(request, 'blog/post_detail.html', {'post': post,'form':form,'comment':comments})
	
def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})
	
def post_edit(request, slug):
	post = get_object_or_404(Post, slug=slug)
	if request.method == "POST":
		form = PostForm(request.POST, request.FILES, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_edit.html', {'form': form})

def signup_request(request):
	if request.method == "POST":
		form = UserForm(request.POST, request.FILES)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("blog:post_list")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = UserForm()
	return render(request=request, template_name="blog/signup.html", context={'form':form})

def login_request(request):
	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			print(user)
			if user:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("blog:post_list")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	else:       
		form = LoginForm()
	return render(request=request, template_name="blog/login.html", context={"form":form})

def logout_request(request):
	logout(request)
	return redirect('blog:login')

def profile_request(request):
	user = get_object_or_404(User, pk=request.user.id)
	return render(request, "blog/profile.html", {'user': user})

def profile_edit(request):
	user = get_object_or_404(User, pk=request.user.id)
	if request.method == "POST":
		form = UserForm(request.POST, request.FILES, instance=user)
		if form.is_valid():
			# user = form.save(commit=False)
			# user.username = request.user
			user.save()
			return redirect('blog:users-profile')
	else:
		form = UserForm(instance=user)
	return render(request, 'blog/signup.html', {'form': form})

def category(request,slug):
	posts = Post.objects.filter(category__slug=slug)
	requested_category = Category.objects.get(slug=slug)
	categories = Category.objects.all()
	tags = Tag.objects.all()

	context = {
		'posts': posts,
		'category': requested_category,
		'categories': categories,
		'tags': tags,}

	return render (request, 'blog/categories.html', context)

def tag(request, slug):
	posts = Post.objects.filter(tag__slug=slug)
	requested_tag = Tag.objects.get(slug=slug)
	categories = Category.objects.all()
	tags = Tag.objects.all()

	context = {
		'posts': posts,
		'tag': requested_tag,
		'categories': categories,
		'tags': tags,
		}
	return render(request, 'blog/tags.html', context)

djangomerge/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="{% static 'django_ckeditor_5/dist/styles.css' %}" type="text/css" media="all" rel="stylesheet">
        <script src="{% static 'django_ckeditor_5/dist/bundle.js' %}"></script>
        <script src="{% static 'js/jquery-1.11.1.js' %}"></script>
        <script src="{% static 'js/rango-jquery.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    </head>
    <body>
        <header class="page-header">
            <div class="d-flex">
                    <h1><a href="/">Django Girls Blog</a></h1>
                <div class = "col md-10" style="text-align: end;">
                    <aside class="actions">
                        {% if user.is_authenticated %}
                            <a class="btn btn-default  float-right" href="{% url 'blog:users-profile' %}">
                                {% include './icons/person-circle.svg' %}
                                <p>Profile</p>
                            </a>
                            <a class="btn btn-default float-right" href="{% url 'blog:logout' %}">
                                {% include './icons/lock.svg' %}
                                <p>Logout</p>
                            </a>
                            <a class="btn btn-default float-right" href="{% url 'blog:post_new' %}">
                                {% include './icons/file-earmark-plus.svg' %}
                                <p>New Post</p>
                            </a>
                            {% else %}
                            <a class="btn btn-default float-right" href="{% url 'blog:login' %}">
                                {% include './icons/unlock.svg' %}
                                <p>Login</p>
                            </a>
                            <a class="btn btn-default float-right" href="{% url 'blog:signup' %}">
                                {% include './icons/person-plus.svg' %}
                                <p>Signup</p>
                            </a><br/>
                        {% endif %}
                    </aside> 
                </div>
            </div>
        </header>
        <main class="mx-5 ">
            <div class="row mx-5">
                <div class="col">
                    {% block content %}
    
                    {% endblock %}
                </div>
            </div>
        </main>
    </body>
</html>

djangomerge/blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block content %}      

<!--Login--> 
<div class="form-control input-block-level">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/signup">Create an account</a>.</p>
</div>

{% endblock %}

djangomerge/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="post">
        <main>
        <img src="{{ post.featured_image.url }}" class="rounded featured-image" alt="{{post.title}}" style="width: 99%;float: left; object-fit: cover;" height= "300" >
        {% if post.published_date %}
            <div  style="text-align: end;margin-right: 30px;">
                <time class="date">
                    {{ post.published_date }}
                </time>
            </div>
        {% endif %}
        <div class="d-flex align-items-center">
            <img src="{{ post.thumbnail_image.url }}" class="img-circle " alt="{{post.title}}" ALIGN=”right” style="width: 100px; height: 100px; object-fit: cover; border-radius: 100%;"> 
            <div class="col" style="margin-left: 20px; ">
                <aside class="actions" style="text-align: end;margin-right: 30px;">
                    {% if user.is_authenticated %}
                        <a class="btn btn-secondary" href="{% url 'blog:post_edit' slug=post.slug %}">
                            {% include './icons/pencil-fill.svg' %}
                        </a>
                    {% endif %}
                </aside> 
                <h4>{{ post.title }}</h4>
                <h6>{{ post.category }}</h6>
            </div>
        </div>
        <br/>
        <div style="text-align: start;">
            <p> {{ post.text|safe }} </p>
        </div>
        <h4>Tags</h4>
        {% for tag in post.tag.all %}
            <border type="border" class="btn btn-dark">{{ tag }}</border>
        {% endfor %}
        <br/>
        <br/>
        <h6>Comments</h6>
        <div class="w-50 p-2">
            <div class="row d-flex justify-content-left">
                <div class="card mb-3">
                    <div class="card-footer py-3 border-0 " style="background-color: #f8f9fa;">
                        <div class="d-flex flex-start ">
                            <img class="rounded-circle shadow-1-strong me-3"
                            src="{{ user.image.url }}" alt="{{post.username}}" width="40"
                            height="40" />
                            <form method="POST" class="post-form mx-5">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="save btn btn-secondary">Submit</button>
                            </form>     
                        </div>
                     </div>
                </div>
                {% for comment in comment %}
                    <div class="card mt3">
                        {% if comment.is_parent %}
                            <div class="mx-2 mt-3"> 
                                <div class="d-flex align-items-center ">
                                    <h6 class="fw-bold text-primary mb-1">{{comment.name}}</h6>
                                    <p class="text-muted small mb-0 mx-3">
                                        {{comment.timestamp}}
                                    </p>
                                </div>
                            </div>
                            <div class="d-flex">
                                <p class="mt-1 mx-1">
                                    {{comment.comment}}
                                </p>
                                <div class="col md-10" style="text-align: end;">
                                    <aside class="actions">
                                        <a class="btn btn-default replay-form" id="formButton-{{ comment.id }}" >
                                            {% include './icons/reply.svg' %}
                                            <!-- <p>Reply</p> -->
                                        </a>
                                    </aside>
                                </div>
                            </div> 
                            <h6 class="mx-4">Replies:</h6>
                            {% for replies in comment.children %}
                                <p class="mb-1">&nbsp; &nbsp; &nbsp;<b>{{ replies.name }} : </b> {{ replies.comment }}</p>
                            {% endfor %}   
                        {% endif %}   
                        <div class="mx-5 mb-4">
                            <form method="POST" class="post-form" id="aptformButton-{{ comment.id }}" style="display: none;">
                                <div class="mx-5 mt-2">
                                    <img class="rounded-circle  me-3"
                                    src="{{ user.image.url }}" alt="{{comment.username}}" width="50"
                                    height="50" />
                                    &nbsp;<label for="comment"><h4>Reply here</h4></label>
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="hidden" name="comment_id" value="{{comment.id}}">
                                    <button type="submit" class=" save btn btn-secondary">Submit</button>
                                </div>
                            </form>
                        </div> 
                    </div>
                {% endfor %}                            
            </div>
        </div>
        </main>
    </article>

    <script>
        $(document).ready(function(){
            $(document).on("click",".replay-form",function(){
                const formId = $(this).attr('id');
                $('#apt'+formId).toggle();
            });
        });
    </script>
{% endblock %}

djangomerge/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="post">
        <h2>Enter post detail</h2>
        <form method="POST" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-secondary">Save</button>
        </form>
    </article>
{% endblock %}
                

djangomerge/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="{% static 'django_ckeditor_5/dist/styles.css' %}" type="text/css" media="all" rel="stylesheet">
        <script src="{% static 'django_ckeditor_5/dist/bundle.js' %}"></script>
    </head>
    <body>
        <header class="page-header">
            <div class="container">
                <h1><a href="/">Django Girls Blog</a></h1>
            </div>
            <h1><a href="/">Django Girls Blog</a></h1>
        </header>

        <main class="container">
            {% block content %}  
            <div class="row">
                {% for post in posts %}  
                    <div class="col-6 ">
                        <div class="card mb-3">
                            <a class="btn btn-default" href="{% url 'blog:post_detail' slug=post.slug %}">
                                <img src="{{ post.thumbnail_image.url }}" class="img-fluid max-width: 100%; and height: auto;" alt="{{post.title}}" style="width: 800px; height: 250px; object-fit: cover;"/>
                                <br/><br/>
                                <div class="text-start mx-2">
                                    <h3 >{{post.title}}</h3>
                                    <h6 >{{post.category}}</h6>
                                    <p >{{post.text|truncatechars_html:200|safe}}</p>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% endblock %}
        </main>
    </body>
</html>

djangomerge/blog/templates/blog/profile.html
{% extends "blog/base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
	<article class="post">
		<aside class="actions">
            {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="{% url 'blog:profile-edit' %}">
                    {% include './icons/plus-square.svg' %}
                </a>
            {% endif %}
		</aside>
		<div class="d-flex">
			<img class="rounded-circle  me-3"
            	src="{{ user.image.url }}" alt="{{post.username}}" width="150"
            	height="150" /> 
        	<h1>This is the profile page for {{user.username}}</h1>
			<hr>
		</div>
		<div class="user-detail">
			<h4 class="text-muted mb-0" style="font-size: 30px">Username:
			{{ user.username }}</h4>
			<h4 class="text-muted mb-0" style="font-size: 30px">Name:
			{{ user.first_name }} {{ user.last_name }}</h4>
			<h4 class="text-muted mb-0" style="font-size: 30px">Email:
			{{ user.email }} </h4>
			<h4 class="text-muted mb-0" style="font-size: 30px">Gender:
			{{ user.gender}} </h4>
			<h4 class="text-muted mb-0" style="font-size: 30px">Mobile Number:
			{{ user.mobile_no}} </h4>
			<h4 class="text-muted mb-0" style="font-size: 30px">City:
			{{ user.city }} </h4>
			<h4 class="text-muted mb-0" style="font-size: 30px">Country:
			{{ user.country}} </h4>
   		</div>
	</article>
{% endblock content %}

djangomerge/blog/templates/blog/profile_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New Profile</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

djangomerge/blog/templates/blog/signup.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="post">
        {% if user.is_authenticated %}
        <h2>New Profile</h2>
        <div class="w-50">
            <form method="POST" class="post-form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-secondary">Save</button>
            </form>
        </div>
        {% else %}
            <h2>SignUp</h2>
            <div class="w-25">
                <form  method="POST" class="post-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p  }} 
                    <button class="btn btn-primary" type="submit">SignUp</button>
                </form> 
            </div>
        {% endif %}
    </article>
{% endblock %}